Replace AvalDimSharding and MeshDimAssignment with the C++ object.
This is a breaking change in the sense that sharding and mesh_mapping fields are lists (instead of the current tuple), but they are immutable (it's a readonly property on the C++ object).
We can either:
- consider this is pretty much some internal API, and it's ok to do this slight breakage, and users that hack into this can adapt easily.
- consider it's public, in which case I can convert the vectors to be tuples on the pybind11-wrapper. If you prefer this, you can say so and I will update the C++.

2 new `# type: ignore` are needed, because mypy does not understand that List[A] is a List[Union[A, B]]:

```
jax/interpreters/pxla.py:1132: error: Argument "mesh_mapping" to "ShardingSpec" has incompatible type "List[Replicated]"; expected "List[Union[ShardedAxis, Replicated]]"  [arg-type]
jax/interpreters/pxla.py:1132: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
```

PiperOrigin-RevId: 352187814